package main

import (
	"fmt"
	"io"
	"os"
	"os/exec"
	"strconv"
	"strings"
	"sync"
	"time"

	"golang.org/x/sys/unix"
)

// Experimental: --paging's "click a thumbnail, press space for a real Quick
// Look window" prototype. Scoped entirely to the --paging prompt (the only
// place macls already reads raw keystrokes interactively), it turns on
// xterm-style mouse click reporting only while blocked at the pager's own
// prompt (see pagerPrompt), maps a reported click back to whichever
// entry's thumbnail sits there (using the same row/column bookkeeping
// already computed to draw thumbnails in the first place), and shells out
// to qlmanage -p -- macOS's own Quick Look panel, a real GUI window --
// when space is next pressed while that entry is still the one last
// clicked.
//
// Deliberately click-gated, not hover-triggered: an earlier version fired
// qlmanage -p just from the mouse passing over a thumbnail, which turned
// out to be dangerous in practice -- qlmanage -p depends on the same
// QuickLook preview-generation service Finder itself uses, and on a real
// machine a single problematic file wedged that shared service badly
// enough to freeze Finder along with it, needing a hard reboot to recover.
// Gating on an actual click (a deliberate, one-at-a-time action, not
// something the mouse can trigger by merely passing across the screen)
// cuts down how easily that can happen again, but does not remove the
// underlying risk: a genuinely bad file can still wedge the same shared
// service even when deliberately clicked. Treat this as inherently
// somewhat risky, independent of anything macls itself can control -- see
// README.

// mouseTrackingEnable/mouseTrackingDisable turn on xterm "normal" mouse
// click reporting (mode 1000: button press/release, never idle motion) in
// SGR extended-coordinate form (mode 1006, so columns/rows past 223 don't
// wrap), and back off again. Always paired with a defer'd disable --
// leaving this on would make the user's shell echo raw mouse escape codes
// after macls exits.
const mouseTrackingEnable = "\033[?1000h\033[?1006h"
const mouseTrackingDisable = "\033[?1000l\033[?1006l"

// waitReadable reports whether f has input ready within d, using poll(2)
// rather than a read deadline (os.File read deadlines aren't reliably
// supported on a real tty character device on every platform).
func waitReadable(f *os.File, d time.Duration) bool {
	fds := []unix.PollFd{{Fd: int32(f.Fd()), Events: unix.POLLIN}}
	n, err := unix.Poll(fds, int(d.Milliseconds()))
	return err == nil && n > 0 && fds[0].Revents&unix.POLLIN != 0
}

// queryCursorRow asks the terminal for the cursor's current absolute row
// (1-based, within the visible screen) via a Device Status Report (DSR,
// \033[6n) and parses the \033[row;colR reply from stdin. fd must already
// be in raw mode. Returns ok=false on any read/parse failure or timeout
// (e.g. a terminal that doesn't answer DSR at all) -- the caller then has
// no way to place mouse reports relative to the page's own content and
// should skip click tracking entirely for this prompt.
func queryCursorRow(f *os.File) (row int, ok bool) {
	os.Stdout.WriteString("\033[6n")
	deadline := time.Now().Add(200 * time.Millisecond)
	var buf []byte
	b := make([]byte, 1)
	for time.Now().Before(deadline) {
		if !waitReadable(f, 50*time.Millisecond) {
			continue
		}
		n, err := f.Read(b)
		if err != nil || n == 0 {
			return 0, false
		}
		buf = append(buf, b[0])
		if b[0] == 'R' {
			break
		}
		if len(buf) > 32 {
			return 0, false
		}
	}
	s := string(buf)
	i := strings.IndexByte(s, '[')
	j := strings.IndexByte(s, ';')
	k := strings.IndexByte(s, 'R')
	if i < 0 || j < 0 || k < 0 || !(i < j && j < k) {
		return 0, false
	}
	n, err := strconv.Atoi(s[i+1 : j])
	if err != nil || n <= 0 {
		return 0, false
	}
	return n, true
}

// escEventKind distinguishes escReader.next()'s possible results.
type escEventKind int

const (
	escEventEOF escEventKind = iota
	escEventKey
	escEventMouseClick
)

// escReader reads raw bytes from an already-raw-mode terminal fd and turns
// them into a stream of plain keys or parsed SGR mouse-click reports,
// silently absorbing any other escape sequence it doesn't understand
// (including SGR mouse release/motion/wheel reports, which this prototype
// has no use for) and re-reading until it has something to return.
//
// A bare Esc keypress and the start of any other CSI escape sequence both
// begin with the same 0x1B byte, so the two are told apart the same way
// most terminal input libraries do: after seeing 0x1B, a short poll(2)
// wait checks whether more bytes are already arriving. A real escape
// sequence (generated by the terminal itself) arrives as one uninterrupted
// burst essentially instantly; a human pressing the Esc key alone leaves
// nothing following it within that window.
type escReader struct {
	f *os.File
}

func newEscReader(f *os.File) *escReader { return &escReader{f: f} }

func (r *escReader) next() (kind escEventKind, key byte, col, row int) {
	buf := make([]byte, 1)
	for {
		n, err := r.f.Read(buf)
		if err != nil || n == 0 {
			return escEventEOF, 0, 0, 0
		}
		if buf[0] != 27 {
			return escEventKey, buf[0], 0, 0
		}
		if !waitReadable(r.f, 20*time.Millisecond) {
			return escEventKey, 27, 0, 0 // bare Esc
		}
		n, err = r.f.Read(buf)
		if err != nil || n == 0 {
			return escEventEOF, 0, 0, 0
		}
		if buf[0] != '[' {
			return escEventKey, 27, 0, 0 // not a CSI sequence; treat as Esc
		}
		seq, ok := r.readCSITail()
		if !ok {
			return escEventEOF, 0, 0, 0
		}
		if len(seq) > 0 && seq[0] == '<' {
			last := seq[len(seq)-1]
			if last == 'M' {
				if cb, cx, cy, ok := parseSGRMouse(seq); ok {
					// A genuine button press: bit 5 (32, motion) and bit 6
					// (64, wheel/extra buttons) both clear. Under mode
					// 1000 (see mouseTrackingEnable) the terminal
					// shouldn't report anything else in the first place,
					// but the check stays defensive regardless. Which
					// button doesn't matter -- any of them selects
					// whatever's under the pointer.
					if cb&32 == 0 && cb&64 == 0 {
						return escEventMouseClick, 0, cx, cy
					}
				}
			}
			// A release ('m'), or anything else this prototype has no use
			// for: fall through and keep reading.
		}
		// Unrecognized/uninteresting CSI sequence: keep reading.
	}
}

// readCSITail reads bytes up to and including a CSI sequence's final byte
// (0x40-0x7E), returning everything after the initial "\033[". ok is false
// on read error/EOF or a sequence longer than expected (defensive cap).
func (r *escReader) readCSITail() (seq []byte, ok bool) {
	b := make([]byte, 1)
	for {
		if !waitReadable(r.f, 20*time.Millisecond) {
			return nil, len(seq) == 0 // timeout mid-sequence: give up entirely
		}
		n, err := r.f.Read(b)
		if err != nil || n == 0 {
			return nil, false
		}
		seq = append(seq, b[0])
		if b[0] >= '@' && b[0] <= '~' {
			return seq, true
		}
		if len(seq) > 32 {
			return seq, true // cap; parseSGRMouse will just reject it
		}
	}
}

// parseSGRMouse parses a "<Cb;Cx;Cy" + M/m SGR mouse report body (seq is
// everything after "\033[", including the leading '<' and trailing M/m) into
// its button code and 1-based column/row.
func parseSGRMouse(seq []byte) (cb, cx, cy int, ok bool) {
	s := string(seq)
	if len(s) < 2 {
		return 0, 0, 0, false
	}
	body := s[1 : len(s)-1] // strip '<' and the trailing M/m
	parts := strings.Split(body, ";")
	if len(parts) != 3 {
		return 0, 0, 0, false
	}
	var err error
	if cb, err = strconv.Atoi(parts[0]); err != nil {
		return 0, 0, 0, false
	}
	if cx, err = strconv.Atoi(parts[1]); err != nil {
		return 0, 0, 0, false
	}
	if cy, err = strconv.Atoi(parts[2]); err != nil {
		return 0, 0, 0, false
	}
	return cb, cx, cy, true
}

// clickEntry maps a terminal cell -- rowsUp (how many rows above
// wherever the cursor sat right after this page's own content was
// printed, before the pager's own prompt itself; see
// waitForContinueClick()'s contentEndRow -- deliberately not the
// cursor's current position, so this stays valid across a redraw()
// call whenever the prompt is redisplayed) and col (1-based terminal
// column) -- to the full path of the thumbnail entry occupying that
// cell (if any) and a redraw closure (see redrawEntryIcon()/
// redrawEntryText()) that re-paints that same entry's own already-
// on-screen highlight border (or name text, in multi-column output)
// with (or without) a highlight, so a click can visibly show which
// entry is currently selected. Built fresh for each page by
// printPaginated()/printPaginatedMulti() from the same row/column
// bookkeeping used to actually draw thumbnails (see
// renderProgressiveImages()/renderProgressiveMultiImages()).
type clickEntry func(rowsUp, col int) (path string, redraw func(highlight bool), ok bool)

// withReverseVideo re-emits s (an entry's own already-colored name/tag
// text) wrapped in SGR 7 (reverse video), keeping it active throughout
// even across s's own internal "\033[0m" resets (printed between one
// colored segment -- a Finder tag, a stripe -- and the next) by
// reasserting "\033[7m" immediately after each one; a plain wrap alone
// would have s's own first internal reset cancel the reverse attribute
// early. Reverse video, rather than a fixed highlight color, adapts
// automatically to whatever the terminal's actual foreground/background
// happen to be, light or dark theme alike.
func withReverseVideo(s string) string {
	return "\033[7m" + strings.ReplaceAll(s, "\033[0m", "\033[0m\033[7m") + "\033[0m"
}

// redrawEntryText builds a clickEntry's own redraw closure for one
// entry's own name/tag text, whose block starts blockTop rows above
// wherever the cursor sat right after this page's own content was
// printed, before the pager's own prompt itself (see
// waitForContinueClick()'s contentEndRow) -- the same reference point
// rowsUp/col already use for resolving a click in the first place. This
// stays valid as the reference point across the whole prompt's lifetime
// (not just the instant it's first displayed) because pagerPrompt is a
// single character: printing it can never itself wrap to a second
// physical row and move the cursor any further than that.
//
// Jumps the cursor blockTop rows up and colRight columns right,
// reprinting text (or, if highlight, the same text wrapped via
// withReverseVideo()), then restoring the cursor exactly where it was via
// DECSC/DECRC, the same as renderProgressiveImages(). text is expected to
// already exclude the entry's own reserved image-column padding --
// colRight is where it starts, right after that padding -- so this never
// touches, let alone erases, the thumbnail drawn there.
func redrawEntryText(blockTop, colRight int, text string) func(highlight bool) {
	return func(highlight bool) {
		out := text
		if highlight {
			out = withReverseVideo(text)
		}
		fmt.Print("\0337") // DECSC: save cursor position
		if blockTop > 0 {
			fmt.Printf("\033[%dA", blockTop)
		}
		fmt.Print("\r")
		if colRight > 0 {
			fmt.Printf("\033[%dC", colRight)
		}
		fmt.Print(out)
		fmt.Print("\0338") // DECRC: restore cursor position
	}
}

// firstLineTextAfterPad returns line's own first physical line (up to any
// embedded "\n" -- see progressiveTextLayout()'s filler suffix) with its
// leading imgColWidth bytes (the entry's own reserved, blank image-column
// padding -- always plain spaces, never containing an escape sequence, so
// slicing by byte count is exact) removed, for redrawEntryText()'s own
// text argument.
func firstLineTextAfterPad(line string, imgColWidth int) string {
	if nl := strings.IndexByte(line, '\n'); nl >= 0 {
		line = line[:nl]
	}
	if len(line) >= imgColWidth {
		return line[imgColWidth:]
	}
	return line
}

// drawnIconHeight is the height (in rows) renderProgressiveImages() actually
// declares for an entry's own thumbnail -- one row less than boxHeight (the
// full height planProgressiveImages() reserved for it), when boxHeight
// leaves room to spare one, so the box's own last row is always left
// blank. redrawEntryIcon() paints that spare row (and the already-blank
// gap column to the icon's own right -- see imgColWidth) in reverse video
// to show a clicked entry's selection, without ever touching the icon's
// own cells: toggling the highlight on or off never needs to re-fetch or
// re-encode the actual image.
func drawnIconHeight(boxHeight int) int {
	if boxHeight > 1 {
		return boxHeight - 1
	}
	return boxHeight
}

// redrawEntryIcon builds a clickEntry's own redraw closure for one entry's
// own thumbnail border, whose box starts blockTop rows above wherever the
// cursor sat right after this page's own content was printed (see
// redrawEntryText()'s own doc comment for that reference point).
//
// boxHeight is the full height planProgressiveImages() reserved for this
// entry's thumbnail; drawnHeight (see drawnIconHeight()) is the shorter
// height the icon itself was actually declared at. Highlighting paints, in
// reverse video, the imgWidth..imgColWidth gap column (already always
// blank -- the spacing before the entry's own name) for every row the icon
// itself occupies, plus a full imgColWidth-wide row below it for any
// row(s) boxHeight left spare beyond drawnHeight -- an "L" border around
// the icon that never overlaps its own cells (nor, on a non-stacked entry
// sharing its first row with the entry's own name text, that name's own
// columns, which start at imgColWidth).
func redrawEntryIcon(blockTop, imgWidth, imgColWidth, drawnHeight, boxHeight int) func(highlight bool) {
	gapCell, fullRow := " ", strings.Repeat(" ", imgColWidth)
	return func(highlight bool) {
		hlGap, hlRow := gapCell, fullRow
		if highlight {
			hlGap = "\033[7m \033[0m"
			hlRow = "\033[7m" + fullRow + "\033[0m"
		}
		for row := 0; row < boxHeight; row++ {
			text, col := hlGap, imgWidth
			if row >= drawnHeight {
				text, col = hlRow, 0
			}
			rowsUp := blockTop - row
			fmt.Print("\0337") // DECSC: save cursor position
			if rowsUp > 0 {
				fmt.Printf("\033[%dA", rowsUp)
			}
			fmt.Print("\r")
			if col > 0 {
				fmt.Printf("\033[%dC", col)
			}
			fmt.Print(text)
			fmt.Print("\0338") // DECRC: restore cursor position
		}
	}
}

// singleColumnClickLookup builds a clickEntry for printPaginated()'s
// -1/-l layout: entries [start, end) are the ones currently visible on
// screen (the page just rendered, plus any single-entry lines added since
// by a return/line advance -- see printPaginated()), and rowsUp for each is
// measured from the bottom entry upward, matching how
// renderProgressiveImages() itself measures rowsUp from wherever the
// cursor currently sits. A stacked entry's whole block (its own text row
// plus every image row below it) counts as that entry for click purposes,
// not just the exact row the image itself draws into. entryLines is
// printPaginated()'s own per-entry rendered text (see
// firstLineTextAfterPad()), imgColWidth its reserved image-column width
// (imgWidth+1). Returns nil if none of [start, end) has a thumbnail at
// all, so the caller can skip mouse tracking entirely for a page with
// nothing to click.
func singleColumnClickLookup(fullPaths, entryLines []string, plans []imagePlan, imgWidth, imgColWidth, start, end int) clickEntry {
	type span struct{ idx, lo, hi int }
	var spans []span
	acc := 0
	for i := end - 1; i >= start; i-- {
		r := plans[i].rows()
		if plans[i].hasImage {
			spans = append(spans, span{idx: i, lo: acc + 1, hi: acc + r})
		}
		acc += r
	}
	if len(spans) == 0 {
		return nil
	}
	return func(rowsUp, col int) (string, func(bool), bool) {
		if col < 1 || col > imgWidth {
			return "", nil, false
		}
		for _, sp := range spans {
			if rowsUp >= sp.lo && rowsUp <= sp.hi {
				boxHeight := plans[sp.idx].height
				redraw := redrawEntryIcon(sp.hi, imgWidth, imgColWidth, drawnIconHeight(boxHeight), boxHeight)
				return fullPaths[sp.idx], redraw, true
			}
		}
		return "", nil, false
	}
}

// multiColumnClickLookup builds a clickEntry for printPaginatedMulti()'s
// multi-column layout. rowOfIdx/colOffsetOfIdx are the whole listing's own
// global (not page-relative) line/column bookkeeping, from
// computeImageCellOffsets(); final is that same listing's own per-entry
// rendered text (see firstLineTextAfterPad()), and lineRows its per-line
// physical row count (see lineRowCounts()) -- almost always 1, except a
// line holding one oversized entry alone, which wraps to more than one
// physical row on its own, same as printPaginated()'s wrapped-line
// entries. visibleLines is how many logical lines have been printed so
// far (the current page's own end, or one more after each line/return
// advance -- see printPaginatedMulti()). Returns nil if nothing visible so
// far has a thumbnail.
//
// Builds spans of rowsUp (rows above the prompt's own line, 1 = the row
// directly above it) per logical line from the bottom up, the same way
// singleColumnClickLookup() does per entry -- a line's own wrapped
// continuation rows count as that line for click purposes, not just its
// first physical row (the only one an image can actually sit on).
func multiColumnClickLookup(fullPaths []string, hasImage []bool, rowOfIdx, colOffsetOfIdx []int, final []string, imgWidth, imgColWidth int, lineRows []int, visibleLines int) clickEntry {
	any := false
	for i := range fullPaths {
		if hasImage[i] && rowOfIdx[i] < visibleLines {
			any = true
			break
		}
	}
	if !any {
		return nil
	}
	type lineSpan struct{ line, lo, hi int }
	var spans []lineSpan
	acc := 0
	for line := visibleLines - 1; line >= 0; line-- {
		r := 1
		if line < len(lineRows) && lineRows[line] > 0 {
			r = lineRows[line]
		}
		spans = append(spans, lineSpan{line: line, lo: acc + 1, hi: acc + r})
		acc += r
	}
	return func(rowsUp, col int) (string, func(bool), bool) {
		if rowsUp < 1 {
			return "", nil, false
		}
		targetLine, targetHi := -1, 0
		for _, sp := range spans {
			if rowsUp >= sp.lo && rowsUp <= sp.hi {
				targetLine, targetHi = sp.line, sp.hi
				break
			}
		}
		if targetLine < 0 {
			return "", nil, false
		}
		for i := range fullPaths {
			if !hasImage[i] || rowOfIdx[i] != targetLine {
				continue
			}
			lo := colOffsetOfIdx[i] + 1
			hi := lo + imgWidth - 1
			if col < lo || col > hi {
				continue
			}
			text := firstLineTextAfterPad(final[i], imgColWidth)
			colRight := colOffsetOfIdx[i] + imgColWidth
			return fullPaths[i], redrawEntryText(targetHi, colRight, text), true
		}
		return "", nil, false
	}
}

// qlProcessMu guards qlProcess, the most recently started qlmanage -p (see
// launchQuickLook()) -- a package-level, not per-prompt or per-page,
// variable: Finder's own Quick Look panel is a single window that swaps to
// whatever's newly selected regardless of which folder that happens in,
// and launchQuickLook() matches that by tracking across the whole run,
// not just the current --paging prompt.
var (
	qlProcessMu sync.Mutex
	qlProcess   *os.Process
)

// launchQuickLook opens path in macOS's own Quick Look panel via
// qlmanage -p -- a real GUI window, independent of and in addition to
// whatever -I has already drawn inline. Started detached (not waited on
// inline) so it doesn't block the pager's own input loop; the goroutine
// just reaps the child once its window is closed to avoid a zombie
// process. No-ops if qlmanage isn't on PATH (e.g. not running on macOS).
//
// Killing whatever qlmanage -p this function itself last started, right
// before starting the new one, matches Finder's own Quick Look behavior:
// selecting a different file swaps the same panel to it rather than
// opening a second one alongside the first. Never touches a qlmanage
// process this function didn't start itself.
//
// See this file's own top-of-file comment: qlmanage -p has been observed,
// on a real machine, to wedge the shared QuickLook service badly enough to
// freeze Finder along with it. Only ever call this for a file the user
// just explicitly clicked -- never from a passive signal like hovering.
func launchQuickLook(path string) {
	qlPath, err := exec.LookPath("qlmanage")
	if err != nil {
		return
	}

	qlProcessMu.Lock()
	defer qlProcessMu.Unlock()
	if qlProcess != nil {
		qlProcess.Kill()
		qlProcess = nil
	}

	cmd := exec.Command(qlPath, "-p", path)
	cmd.Stdout = io.Discard
	cmd.Stderr = io.Discard
	if err := cmd.Start(); err != nil {
		return
	}
	qlProcess = cmd.Process
	go cmd.Wait()
}
